### ISSUE TITLE
How to collect all articles since $date ?

### ISSUE THREAD

**Issue by classofoutcasts** [xiffy/dcrrspndnt#9]
Now it only fetches about 25 articles on the very first run, is there a way to collect all tweets from - let's say - the last 2 years ?

**Comment by xiffy** [comment]
With the normal search api of twitter, you just can't as far as i know. from the docs:

> The Twitter Search API is part of Twitter’s REST API. It allows queries against the indices of recent or popular Tweets and behaves similarly to, but not exactly like the Search feature available in Twitter mobile or web clients, such as Twitter.com search. The Twitter Search API searches against a sampling of recent Tweets published in the past 7 days.
Tou might be lucky to get the streaming api to get to work for you, i never bothered.. https://dev.twitter.com/streaming/overview

**Comment by classofoutcasts** [comment]
I was afraid so, but thanks for the explanation anyways.
Would you consider adding an up-to-date export of the database records on molecule.nl to the repo? I know it's possible to give curl a go at that, but thought asking you directly was nicer ;)
It would be a nice starting point for people installing your project.

**Comment by xiffy** [comment]
Yes, but no.
